-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('DEPOSIT', 'EXPENSE', 'INVESTMENT');

-- CreateEnum
CREATE TYPE "TransactionCategory" AS ENUM ('HOUSING', 'RENT', 'MORTGAGE', 'WATER', 'ELECTRICITY', 'INTERNET', 'GAS', 'TRANSPORTATION', 'FUEL', 'PUBLIC_TRANSPORT', 'VEHICLE_MAINTENANCE', 'FOOD', 'GROCERIES', 'RESTAURANTS', 'ENTERTAINMENT', 'STREAMING_SERVICES', 'MOVIES', 'HEALTH', 'MEDICAL_EXPENSES', 'PHARMACY', 'GYM', 'DENTIST', 'MEDICAL_EXAMS', 'HEALTH_INSURANCE', 'TREATMENTS_THERAPIES', 'UTILITY', 'PHONE_BILL', 'SALARY', 'EDUCATION', 'SCHOOL_FEES', 'COURSES', 'OTHER', 'INVESTMENTS', 'LEISURE', 'CLOTHING', 'SUBSCRIPTIONS_SERVICES', 'TAXES_FEES', 'DONATIONS_CHARITY', 'PERSONAL_CARE', 'TECHNOLOGY_ELECTRONICS', 'TRAVEL_TOURISM', 'MAINTENANCE_REPAIRS', 'PETS', 'DEBTS_LOANS', 'TOOLS_EQUIPMENT');

-- CreateEnum
CREATE TYPE "TransactionPaymentMethod" AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'BANK_SLIP', 'CASH', 'PIX', 'PAYPAL', 'CRYPTOCURRENCY', 'CHECK', 'GOOGLE_PAY', 'APPLE_PAY', 'GIFT_CARD', 'STORE_CREDIT', 'OTHER');

-- CreateTable
CREATE TABLE "Transaction" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "TransactionType" NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "category" "TransactionCategory" NOT NULL,
    "paymentMethod" "TransactionPaymentMethod" NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" TEXT NOT NULL,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "email" TEXT NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
