import { TransactionCategory, TransactionPaymentMethod, TransactionType } from "@prisma/client";

export const TRANSACTION_CATEGORY_LABELS = {
  [TransactionCategory.HOUSING]: "Moradia",
  [TransactionCategory.RENT]: "Aluguel",
  [TransactionCategory.MORTGAGE]: "Hipoteca",
  [TransactionCategory.WATER]: "Água",
  [TransactionCategory.ELECTRICITY]: "Luz",
  [TransactionCategory.INTERNET]: "Internet",
  [TransactionCategory.GAS]: "Gás",
  [TransactionCategory.TRANSPORTATION]: "Transporte",
  [TransactionCategory.FUEL]: "Combustível",
  [TransactionCategory.PUBLIC_TRANSPORT]: "Transporte Público",
  [TransactionCategory.VEHICLE_MAINTENANCE]: "Manutenção Veicular",
  [TransactionCategory.FOOD]: "Alimentação",
  [TransactionCategory.GROCERIES]: "Mercado",
  [TransactionCategory.RESTAURANTS]: "Restaurantes",
  [TransactionCategory.ENTERTAINMENT]: "Entretenimento",
  [TransactionCategory.STREAMING_SERVICES]: "Serviços de Streaming",
  [TransactionCategory.MOVIES]: "Cinema/Filmes",
  [TransactionCategory.HEALTH]: "Saúde",
  [TransactionCategory.MEDICAL_EXPENSES]: "Despesas Médicas",
  [TransactionCategory.PHARMACY]: "Farmácia",
  [TransactionCategory.GYM]: "Academia",
  [TransactionCategory.DENTIST]: "Dentista",
  [TransactionCategory.MEDICAL_EXAMS]: "Exames Médicos",
  [TransactionCategory.HEALTH_INSURANCE]: "Seguro de Saúde",
  [TransactionCategory.TREATMENTS_THERAPIES]: "Tratamentos e Terapias",
  [TransactionCategory.EDUCATION]: "Educação",
  [TransactionCategory.SCHOOL_FEES]: "Mensalidade Escolar",
  [TransactionCategory.COURSES]: "Cursos",
  [TransactionCategory.OTHER]: "Outros",
  [TransactionCategory.INVESTMENTS]: "Investimentos",
  [TransactionCategory.LEISURE]: "Lazer",
  [TransactionCategory.CLOTHING]: "Vestuário",
  [TransactionCategory.SUBSCRIPTIONS_SERVICES]: "Assinaturas e Serviços",
  [TransactionCategory.TAXES_FEES]: "Impostos e Taxas",
  [TransactionCategory.DONATIONS_CHARITY]: "Doações e Caridade",
  [TransactionCategory.PERSONAL_CARE]: "Cuidados Pessoais",
  [TransactionCategory.TECHNOLOGY_ELECTRONICS]: "Tecnologia e Eletrônicos",
  [TransactionCategory.TRAVEL_TOURISM]: "Viagens e Turismo",
  [TransactionCategory.MAINTENANCE_REPAIRS]: "Manutenção e Reparos",
  [TransactionCategory.PETS]: "Animais de Estimação",
  [TransactionCategory.DEBTS_LOANS]: "Dívidas e Empréstimos",
  [TransactionCategory.TOOLS_EQUIPMENT]: "Ferramentas e Equipamentos",
};

export const TRANSACTION_PAYMENT_METHOD_LABELS = {
  [TransactionPaymentMethod.CASH]: "Dinheiro",
  [TransactionPaymentMethod.CREDIT_CARD]: "Cartão de Crédito",
  [TransactionPaymentMethod.DEBIT_CARD]: "Cartão de Débito",
  [TransactionPaymentMethod.BANK_TRANSFER]: "Transferência Bancária",
  [TransactionPaymentMethod.BANK_SLIP]: "Boleto Bancário",
  [TransactionPaymentMethod.PIX]: "Pix",
  [TransactionPaymentMethod.PAYPAL]: "PayPal",
  [TransactionPaymentMethod.CRYPTOCURRENCY]: "Criptomoeda",
  [TransactionPaymentMethod.CHECK]: "Cheque",
  [TransactionPaymentMethod.GOOGLE_PAY]: "Google Pay",
  [TransactionPaymentMethod.APPLE_PAY]: "Apple Pay",
  [TransactionPaymentMethod.GIFT_CARD]: "Vale-Presente",
  [TransactionPaymentMethod.STORE_CREDIT]: "Crédito na Loja",
  [TransactionPaymentMethod.OTHER]: "Outro",
};

export const TRANSACTION_PAYMENT_METHOD_ICONS = [
  { value: TransactionPaymentMethod.CREDIT_CARD, icon: "credit-card.svg" },
  { value: TransactionPaymentMethod.DEBIT_CARD, icon: "debit-card.svg" },
  { value: TransactionPaymentMethod.BANK_TRANSFER, icon: "bank-transfer.svg" },
  { value: TransactionPaymentMethod.BANK_SLIP, icon: "bank-slip.svg" },
  { value: TransactionPaymentMethod.CASH, icon: "money.svg" },
  { value: TransactionPaymentMethod.PIX, icon: "pix.svg" },
  { value: TransactionPaymentMethod.PAYPAL, icon: "paypal.svg" },
  { value: TransactionPaymentMethod.CRYPTOCURRENCY, icon: "crypto.svg" },
  { value: TransactionPaymentMethod.CHECK, icon: "check.svg" },
  { value: TransactionPaymentMethod.GOOGLE_PAY, icon: "google-pay.svg" },
  { value: TransactionPaymentMethod.APPLE_PAY, icon: "apple-pay.svg" },
  { value: TransactionPaymentMethod.GIFT_CARD, icon: "gift-card.svg" },
  { value: TransactionPaymentMethod.STORE_CREDIT, icon: "store-credit.svg" },
  { value: TransactionPaymentMethod.OTHER, icon: "other.svg" },
];

export const TRANSACTION_TYPE_OPTIONS = [
  { value: TransactionType.EXPENSE, label: "Despesa" },
  { value: TransactionType.DEPOSIT, label: "Depósito" },
  { value: TransactionType.INVESTMENT, label: "Investimento" },
];

export const TRANSACTION_CATEGORY_OPTIONS = [
  { value: TransactionCategory.HOUSING, label: "Moradia" },
  { value: TransactionCategory.RENT, label: "Aluguel" },
  { value: TransactionCategory.MORTGAGE, label: "Hipoteca" },
  { value: TransactionCategory.WATER, label: "Água" },
  { value: TransactionCategory.ELECTRICITY, label: "Luz" },
  { value: TransactionCategory.INTERNET, label: "Internet" },
  { value: TransactionCategory.GAS, label: "Gás" },
  { value: TransactionCategory.TRANSPORTATION, label: "Transporte" },
  { value: TransactionCategory.FUEL, label: "Combustível" },
  { value: TransactionCategory.PUBLIC_TRANSPORT, label: "Transporte Público" },
  { value: TransactionCategory.VEHICLE_MAINTENANCE, label: "Manutenção Veicular" },
  { value: TransactionCategory.FOOD, label: "Alimentação" },
  { value: TransactionCategory.GROCERIES, label: "Mercado" },
  { value: TransactionCategory.RESTAURANTS, label: "Restaurantes" },
  { value: TransactionCategory.ENTERTAINMENT, label: "Entretenimento" },
  { value: TransactionCategory.STREAMING_SERVICES, label: "Serviços de Streaming" },
  { value: TransactionCategory.MOVIES, label: "Cinema/Filmes" },
  { value: TransactionCategory.HEALTH, label: "Saúde" },
  { value: TransactionCategory.MEDICAL_EXPENSES, label: "Despesas Médicas" },
  { value: TransactionCategory.PHARMACY, label: "Farmácia" },
  { value: TransactionCategory.GYM, label: "Academia" },
  { value: TransactionCategory.DENTIST, label: "Dentista" },
  { value: TransactionCategory.MEDICAL_EXAMS, label: "Exames Médicos" },
  { value: TransactionCategory.HEALTH_INSURANCE, label: "Seguro de Saúde" },
  { value: TransactionCategory.TREATMENTS_THERAPIES, label: "Tratamentos e Terapias" },
  { value: TransactionCategory.EDUCATION, label: "Educação" },
  { value: TransactionCategory.SCHOOL_FEES, label: "Mensalidade Escolar" },
  { value: TransactionCategory.COURSES, label: "Cursos" },
  { value: TransactionCategory.OTHER, label: "Outros" },
  { value: TransactionCategory.INVESTMENTS, label: "Investimentos" },
  { value: TransactionCategory.LEISURE, label: "Lazer" },
  { value: TransactionCategory.CLOTHING, label: "Vestuário" },
  { value: TransactionCategory.SUBSCRIPTIONS_SERVICES, label: "Assinaturas e Serviços" },
  { value: TransactionCategory.TAXES_FEES, label: "Impostos e Taxas" },
  { value: TransactionCategory.DONATIONS_CHARITY, label: "Doações e Caridade" },
  { value: TransactionCategory.PERSONAL_CARE, label: "Cuidados Pessoais" },
  { value: TransactionCategory.TECHNOLOGY_ELECTRONICS, label: "Tecnologia e Eletrônicos" },
  { value: TransactionCategory.TRAVEL_TOURISM, label: "Viagens e Turismo" },
  { value: TransactionCategory.MAINTENANCE_REPAIRS, label: "Manutenção e Reparos" },
  { value: TransactionCategory.PETS, label: "Animais de Estimação" },
  { value: TransactionCategory.DEBTS_LOANS, label: "Dívidas e Empréstimos" },
  { value: TransactionCategory.TOOLS_EQUIPMENT, label: "Ferramentas e Equipamentos" },
];

export const TRANSACTION_PAYMENT_METHOD_OPTIONS = [
  { value: TransactionPaymentMethod.CASH, label: "Dinheiro" },
  { value: TransactionPaymentMethod.CREDIT_CARD, label: "Cartão de Crédito" },
  { value: TransactionPaymentMethod.DEBIT_CARD, label: "Cartão de Débito" },
  { value: TransactionPaymentMethod.BANK_TRANSFER, label: "Transferência Bancária" },
  { value: TransactionPaymentMethod.BANK_SLIP, label: "Boleto Bancário" },
  { value: TransactionPaymentMethod.PIX, label: "Pix" },
  { value: TransactionPaymentMethod.PAYPAL, label: "PayPal" },
  { value: TransactionPaymentMethod.CRYPTOCURRENCY, label: "Criptomoeda" },
  { value: TransactionPaymentMethod.CHECK, label: "Cheque" },
  { value: TransactionPaymentMethod.GOOGLE_PAY, label: "Google Pay" },
  { value: TransactionPaymentMethod.APPLE_PAY, label: "Apple Pay" },
  { value: TransactionPaymentMethod.GIFT_CARD, label: "Vale-Presente" },
  { value: TransactionPaymentMethod.STORE_CREDIT, label: "Crédito na Loja" },
  { value: TransactionPaymentMethod.OTHER, label: "Outro" },
];